name: Build (eng)
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile.build \
            --build-arg QT_USERNAME=${{ secrets.QT_USERNAME }} \
            --build-arg QT_PASSWORD=${{ secrets.QT_PASSWORD }} \
            --build-arg BUILD_TYPE=${{ github.event.inputs.build_type }} \
            -t calculator-build .
      - name: Extract artifacts from container
        run: |
          docker create --name tmp_container calculator-build
          docker cp tmp_container:/app/artifacts ./artifacts
          docker rm tmp_container
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eng-build-${{ github.run_id }}
          path: ./artifacts
          retention-days: 7
      - name: Clean up Docker image
        run: |
          docker rmi calculator-build || true
          docker system prune -f || true
