#ifndef CALCULATOR_UI_H
#define CALCULATOR_UI_H

#include <memory>
#include "calculator.hpp"
// generated by Qt User Interface Compiler version 6.9.1
#include "calculator_gen_ui.hpp"

namespace Ui {
    class CalculatorUi: protected CalculatorMainWindow {
    private:
        Calculator &calculator;
        std::unique_ptr<QMainWindow> mainWindow;
        void connectButtons();
        /**
         * Handles keyboard button clicks in the calculator UI.
         * This function processes the text of the button clicked and updates the result browser accordingly.
         * It supports operations like addition, subtraction, multiplication, division, and special functions
         * like square root and factorial. It also handles clearing the input, evaluating the expression, and
         * managing errors.
         * @param resultBrowser The QTextBrowser where the result is displayed.
         * @param text The text of the button clicked, which determines the action to perform.
         *              It can be a number, an operator, or a special command like "AC" or "=".
         *              Supported operators include "+", "-", "*", "/", "^", "sqrt", "pi", and
         *              "sep" (for decimal point). Special commands include "AC" (clear all),
         *              "=" (evaluate expression), "x" (multiplication), "<<" (remove last character),
         *              and "pi" (insert the value of pi).
         * @throws InvalidExpression If the expression is invalid or unsupported.
         * @throws std::runtime_error If an unexpected error occurs during evaluation.
         * @note The function resets the calculator state after evaluating an expression or encountering
         * an error.
         * @note The function also handles special cases like removing the last character from the input
         * and inserting the value of pi.
         * @note The function prevents starting an expression with an operator to ensure valid input.
         * @note The function uses the calculator's expression evaluation method to compute the result
         * and updates the result browser accordingly.
         */
        void keyboardButtonClicked(QTextBrowser* resultBrowser, const QString& text);
    public:
        /**
         * Constructor for the CalculatorUi class.
         * Initializes the main window and sets up the calculator reference.
         * @param calculator Reference to the Calculator instance used for expression evaluation.
         */
        CalculatorUi(Calculator &calculator);
        /**
         * Destructor for the CalculatorUi class.
         */
        ~CalculatorUi() = default;
        /**
         * Sets up the user interface for the calculator.
         * This function initializes the main window and sets up the UI components such as buttons,
         * result browser, and layout. It also connects the buttons to their respective actions.
         */
        void setup();
        /**
         * Returns the main window of the calculator UI.
         * @return Pointer to the QMainWindow instance representing the main window.
         */
        QMainWindow* getMainWindow() const;
    };
} // namespace Ui

#endif /* !CALCULATOR_UI_H! */
